//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int SaleId { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> SaleCustomerId { get; set; }
        public Nullable<int> SaleProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
